package enums;

public enum Tokens {
	//Literals
	STRING, ID, INTEGER, FLOAT,
	//Keywords
	TRUE, FALSE, GIZ, FETTLE, GIVEOVER, OVER, NONE, PROMPT, READ, WRITE, AND, OR, NOT, 
	IF, THEN, ELSE, WHEN, GOWAN, WANG, WHILE, ALLUS, GANDER, FORGET, EYUP, SUMMAT,
	NUMBER, LETTER, SCRIPT, ANSWER,
	//Symbols
	PERIOD, L_PAREN, R_PAREN, SM, COMMA, COLON, DOLLA, FSLASH, EQUAL, PLUS, MINUS, STAR,
	PERCENT, LC_BRACKET, RC_BRACKET, LS_BRACKET, RS_BRACKET, LESS, GREAT, EXCLAMATION, COLON_EQ,
	LESS_EQ, GREAT_EQ, EXCLA_EQ,
	
	ERROR, EOI
}
